project_name: restify
before:
  hooks:
    - go mod download
builds:
  - binary: restify
    main: ./cmd
    env:
      # to allow for alpine/musl use
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
changelog:
  filters:
    exclude:
      - '^build:'
      - '^ci:'
dockers:
  - image_templates:
      - "itzg/restify:latest"
      - "itzg/restify:{{.Tag}}"
    goos: linux
    goarch: amd64
# alpine base image relies on https://github.com/docker-library/official-images#architectures-other-than-amd64
#  - image_templates:
#      - "itzg/restify:arm64"
#      - "itzg/restify:{{.Tag}}-arm64"
#    goos: linux
#    goarch: arm64
scoop:
  bucket:
    owner: itzg
    name: scoop-bucket
  folder: bucket
  license: Apache2
  description: Enables REST-like access to HTML pages by scraping and parsing them into JSON